Errors when adding matrices

Import relevant libraries

In [13]:
import numpy as np

Addition

Addition of scalars

In [17]:
5 + 5

10

In [19]:
10 - 4 

6

In order to add vectors and matrices their forms must match

Addition of matrices

In [23]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [25]:
m2 = np.array([[5,3],
       [-2,4]])
m2

array([[ 5,  3],
       [-2,  4]])

In [27]:
m1 + m2 

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

Addition of vectors

Same goes for vectors


Exceptions (addition with a scalar)

In [32]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [34]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [36]:
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [38]:
v1 + 1

array([2, 3, 4, 5, 6])

In [40]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [42]:
v1 + np.array ([1])

array([2, 3, 4, 5, 6])

Transpose of a matrix

In [45]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [47]:
m1.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [49]:
m2

array([[ 5,  3],
       [-2,  4]])

In [51]:
m1.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [53]:
m2 

array([[ 5,  3],
       [-2,  4]])

In [55]:
m2.T

array([[ 5, -2],
       [ 3,  4]])

In [59]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [61]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

Transposing scalars

any scalar when transposed equals itself

In [65]:
s = np.array([5])

In [67]:
s.T

array([5])

Transposing vectors

In [70]:
v1

array([1, 2, 3, 4, 5])

In [72]:
v1.T

array([1, 2, 3, 4, 5])

in python one dimensional arrays do not get transposed

In [77]:
v1.shape

(5,)

In [79]:
v1_reshaped = v1.reshape(1,5)
v1_reshaped

array([[1, 2, 3, 4, 5]])

In [83]:
v1_reshaped.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

Multiplication

Dot product is the sum of the product of the corresponding elements

Dot product

In [90]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [92]:
np.dot(x,y)

-66

In [94]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [96]:
np.dot(u,v)

18

scalar * scalar

In [99]:
np.dot(5,6)

30

In [101]:
np.dot(10,-2)

-20

scalar * vector

In [105]:
x

array([ 2,  8, -4])

In [107]:
5 * x

array([ 10,  40, -20])

Dot product of matrices

In [110]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

Scalar* matrix

In [113]:
3 * m1

array([[15, 36, 18],
       [-9,  0, 42]])

matrix * matrix

we can only multiply an mxn matrix with a n x k matrix

In [117]:
m3 = np.array([[2,8,3], [-1,0,0]])
m3

array([[ 2,  8,  3],
       [-1,  0,  0]])

In [119]:
m3.T

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [123]:
np.dot(m1,m3.T)

array([[124,  -5],
       [ 36,   3]])

In [125]:
D = np.array([[-12,5,-5,1,6],[6,-2,0,0,3],[10,2,0,8,0],[9,-4,8,3,-6]])
D

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,   3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [129]:
E = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
E

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [131]:
np.dot(D,E)

array([[-71, -48],
       [  2, -25],
       [132,  14],
       [ 95,  57]])