using NumPy

In [2]:
import numpy as np

Ndarray

In [5]:
array_a = np.array([1,2,3])

In [7]:
array_a

array([1, 2, 3])

In [9]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

N-D arrays are useful because they are the easiest way to use linear algebra in python

one can conduct element wise operations on them

NumPy Documentation

https//numpy.org/devdocs/

In [17]:
np.mean(array_b, axis = 0)

array([2.5, 3.5, 4.5])