Tensors can be stored in ndarrays, and thats how we often deal with the issue

Import the relevant libraries

In [5]:
import numpy as np

Creating a tensor

In [7]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [13]:
m2 = ([[9,8,7],[1,3,-5]])
m2

[[9, 8, 7], [1, 3, -5]]

Addition

In [15]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

Subtraction

In [19]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

In [17]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

Checking its shape

In [17]:
t.shape

(2, 2, 3)

Manually creating a tensor

In [20]:
t_manual = np.array([[[5,12,6], [-3,0,14]],[[9,8,7],[1,3,-5]]])
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

Adding vectors together

In [26]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [28]:
v1 + v2

array([6, 6, 6, 6, 6])

Difference

In [31]:
v1 - v2

array([-4, -2,  0,  2,  4])